using ITDeviceManager.Common;
using ITDeviceManager.Data;
using ITDeviceManager.Models;
using Microsoft.EntityFrameworkCore;

namespace ITDeviceManager.Forms;

public class AssignmentEditForm : AppForm
{
    private readonly DarkComboBox _device=new(){Width=300,DropDownStyle=ComboBoxStyle.DropDownList};private readonly DarkComboBox _employee=new(){Width=300,DropDownStyle=ComboBoxStyle.DropDownList};private readonly DateInput _date=new(){Width=180,Value=DateTime.Today};private readonly TextBox _note=new(){Width=300,Height=70,Multiline=true};
    public AssignmentEditForm(){Text="Cấp phát thiết bị";StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;ClientSize=new Size(520,340);Font=new Font("Segoe UI",10);var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Padding=new Padding(24)};t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,140));t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Add(t,"Thiết bị *",_device,52);Add(t,"Nhân viên *",_employee,52);Add(t,"Ngày cấp *",_date,52);Add(t,"Ghi chú",_note,90);var p=new FlowLayoutPanel{AutoSize=true};var save=new Button{Text="Cấp phát",Width=110};var cancel=new Button{Text="Hủy",Width=100,DialogResult=DialogResult.Cancel};p.Controls.AddRange([save,cancel]);var buttonRow=t.RowCount++;t.RowStyles.Add(new RowStyle(SizeType.Absolute,52));t.Controls.Add(new Label(),0,buttonRow);t.Controls.Add(p,1,buttonRow);Controls.Add(t);CancelButton=cancel;Load+=LoadAsync;save.Click+=SaveAsync;}
    private static void Add(TableLayoutPanel t,string label,Control c,int h){var r=t.RowCount++;t.RowStyles.Add(new RowStyle(SizeType.Absolute,h));t.Controls.Add(new Label{Text=label,AutoSize=true,Margin=new Padding(3,10,3,3)},0,r);t.Controls.Add(c,1,r);}
    private async void LoadAsync(object? s,EventArgs e){await using var db=new AppDbContext();var devices=await db.Devices.AsNoTracking().Where(x=>x.Status==DeviceStatus.Available).OrderBy(x=>x.Code).Select(x=>new{ x.Id,Display=x.Code+" - "+x.Name}).ToListAsync();_device.DataSource=devices;_device.DisplayMember="Display";_device.ValueMember="Id";var employees=await db.Employees.AsNoTracking().OrderBy(x=>x.Code).Select(x=>new{x.Id,Display=x.Code+" - "+x.FullName+" ("+x.Department.Name+")"}).ToListAsync();_employee.DataSource=employees;_employee.DisplayMember="Display";_employee.ValueMember="Id";}
    private async void SaveAsync(object? s,EventArgs e){if(_device.SelectedValue is not int deviceId||_employee.SelectedValue is not int employeeId){MessageBox.Show("Cần có ít nhất một thiết bị chưa sử dụng và một nhân viên.");return;}if(!_date.TryGetValue(out var assignedDate)){MessageBox.Show("Ngày cấp phải có dạng dd/MM/yyyy.");_date.FocusInput();return;}if(assignedDate.Date>DateTime.Today){MessageBox.Show("Ngày cấp không được lớn hơn ngày hiện tại.");return;}await using var db=new AppDbContext();var device=await db.Devices.FindAsync(deviceId);var employee=await db.Employees.FindAsync(employeeId);if(device is null||employee is null)return;if(device.Status!=DeviceStatus.Available){MessageBox.Show("Thiết bị không còn ở trạng thái Chưa sử dụng.");return;}db.DeviceAssignments.Add(new DeviceAssignment{DeviceId=deviceId,EmployeeId=employeeId,AssignedDate=assignedDate.Date,Note=string.IsNullOrWhiteSpace(_note.Text)?null:_note.Text.Trim()});device.Status=DeviceStatus.InUse;device.DepartmentId=employee.DepartmentId;await db.SaveChangesAsync();DialogResult=DialogResult.OK;Close();}
}
